# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Metropolis within Gibbs Sampler
#'
#' @param niter number of iterations
#' @return Posterior sample in the transformed space
#' @export
MetropoliswGibbs <- function(niter, parwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration) {
    .Call(`_PIPScreening_MetropoliswGibbs`, niter, parwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration)
}

Metropolis <- function(niter, covwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration) {
    .Call(`_PIPScreening_Metropolis`, niter, covwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration)
}

MCMC <- function(niterMwG, niterMH, parwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration) {
    .Call(`_PIPScreening_MCMC`, niterMwG, niterMH, parwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration)
}

