# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
loglikcpp <- function(rho, sigerr, sigdelta, Rexp, tensD, alpha) {
    .Call(`_PIPScreening_loglikcpp`, rho, sigerr, sigdelta, Rexp, tensD, alpha)
}

#' Metropolis within Gibbs Sampler
#'
#' @param niter number of iterations
#' @param parwalk vector of variances for the random walk
#' @param parinit vector of initial parameters rhos, variance of the observation noise,
#' variance of the discrepancy and (if calibration) thetas
#' @param Rexp residual of field data vs simulator
#' @param tdensD output of the function tensordist
#' @param alpha power in the exponential kernel
#' @param parprior prior parameters for the parameters
#' @param adaptive boolean to adapt the random walk
#' @param calibration list of needed field if a calibration is to be
#'  performed in this order 1) computer model, 2) field observation, 3) field variable, 4) boolean indicating whether calibration
#'  is to be performed or not.
#' @return Posterior sample in the transformed space
#' @export
MetropoliswGibbs <- function(niter, parwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration) {
    .Call(`_PIPScreening_MetropoliswGibbs`, niter, parwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration)
}

#' Metropolis classic sampler with given covariance for RW
#'
#' @param niter number of iterations
#' @param covwalk covariance matrix for random walk
#' @param parinit vector of initial parameters rhos, variance of the observation noise,
#' variance of the discrepancy and (if calibration) thetas
#' @param Rexp residual of field data vs simulator
#' @param tdensD output of the function tensordist
#' @param alpha power in the exponential kernel
#' @param parprior prior parameters for the parameters
#' @param adaptive boolean to adapt the random walk
#' @param calibration list of needed field if a calibration is to be
#'  performed in this order 1) computer model, 2) field observation, 3) field variable, 4) boolean indicating whether calibration
#'  is to be performed or not.
#' @return Posterior sample in the transformed space
#' @export
Metropolis <- function(niter, covwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration) {
    .Call(`_PIPScreening_Metropolis`, niter, covwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration)
}

#' Metropolis sampler after a Metropolis within Gibbs Sampler
#'
#' @param niterMwG number of iterations of the Metropolis withing Gibbss algorithm mainly used to
#'  infer a covariance matrix for the random walk in the upcoming MH algorithm
#' @param niterMH number of iterations of the Metropolis Hastings algorithm
#' @param parwalk vector of variances for the random walk
#' @param parinit vector of initial parameters rhos, variance of the observation noise,
#' variance of the discrepancy and (if calibration) thetas
#' @param Rexp residual of field data vs simulator
#' @param tdensD output of the function tensordist
#' @param alpha power in the exponential kernel
#' @param parprior prior parameters for the parameters
#' @param adaptive boolean to adapt the random walk
#' @param calibration list of needed field if a calibration is to be
#'  performed in this order 1) computer model, 2) field observation, 3) field variable, 4) boolean indicating whether calibration
#'  is to be performed or not.
#' @return Posterior sample in the transformed space
#' @details The MwG sampler is used to estimate a covariance matrix for the random walk in the upcoming Metropolis sampler.
#' @export
MCMC <- function(niterMwG, niterMH, parwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration) {
    .Call(`_PIPScreening_MCMC`, niterMwG, niterMH, parwalk, parinit, Rexp, tdensD, alpha, parprior, adaptive, calibration)
}

